### PR TITLE
Query search results dynamically

### PR DESCRIPTION
**Pull request by nicholaspad**
* Search results are dynamically queried as the user types
    * The query length must be >=3 characters for the search to begin - I settled on 3 characters because the shortest queries are highly likely to be just a department code (e.g. COS, AMS, etc.) which is 3 characters, or a meaningful word which is usually >=3 characters (i.e. not the word "the")
    * [Recal](https://recal.io) has the same search behavior
    * Querying with <3 characters also takes a long time
* Search button is removed
* Pressing "return/enter" will disable focus from the search field
    * On mobile, this will close the keyboard
* Reloading the page when a search result is selected now persists the border around the selected card

## Desktop demo
https://user-images.githubusercontent.com/13815069/132276913-60aec4a1-6725-40b6-aeaf-8357ce8da45d.mov

## Mobile demo
https://user-images.githubusercontent.com/13815069/132277447-f015b5c3-b5db-4137-a055-5e18105f0265.mov

### CODE REVIEW

**Review by shannon-heh — CHANGES_REQUESTED** [review]
looks amazing! one suggestion is to tell users to enter 3+ characters to start searching. e.g. instead of "Search for Courses Above", we can say "Enter 3 characters to start searching for courses!" or something like that. 

image

**Comment by bzzbbz** [comment]
> looks amazing! one suggestion is to tell users to enter 3+ characters to start searching. e.g. instead of "Search for Courses Above", we can say "Enter 3 characters to start searching for courses!" or something like that.
> 
> image

How about Search for a course number or course title

**Comment by nicholaspad** [comment]
@bzzbbz if you hover over the search field, we already say something like that:
image

**Comment by bzzbbz** [comment]
ok then I feel like just saying search for courses is fine, it might be a bit redundant to say enter 3+ characters

**Comment by nicholaspad** [comment]
> ok then I feel like just saying search for courses is fine, it might be a bit redundant to say enter 3+ characters

how is it redundant? where else does it say to enter 3+ chars?

**Review by shannon-heh — APPROVED** [review]

**Pull request merged**
