### PR TITLE
Add SendGrid email template

### PR DESCRIPTION
**Pull request by nicholaspad**
This PR replaces the raw HTML open-spot notifications, instead using SendGrid Dynamic Templates (built using the web interface on the SendGrid dashboard). Dynamic Templates are essentially templates with placeholders, and you use the SendGrid API to specify what you want to fill into those placeholders. The actual code implementation is much simpler than what we currently have.

To view the template itself, go to SendGrid (https://app.sendgrid.com/) -> Email API on the left -> Dynamic Templates -> Open Spot Notification -> Version 1.

I made a single template that covers the four types of open-spot emails. I tried to preserve the central purpose of these emails, which is to tell users of an open spot in a particular section (it's the very first sentence).

1. Open spot in course **with** reserved seating + user has auto-resub **on**
2. Open spot in course **without** reserved seating + user has auto-resub **on**
3. Open spot in course **with** reserved seating + user has auto-resub **off**
4. Open spot in course **without** reserved seating + user has auto-resub **off**

We can change anything within the email, including the image, the buttons/links, the alignment, and the placement of text. Here's what the emails look like:

### Open spot in course **with** reserved seating + user has auto-resub **on**
reserved auto-resub

### Open spot in course **without** reserved seating + user has auto-resub **on**
non-reserved autoresub

### Open spot in course **with** reserved seating + user has auto-resub **off**
reserved non-autoresub

### Open spot in course **without** reserved seating + user has auto-resub **off**
non-reserved non-autoresub

### The emails are also responsive
mobile responsiveness

### CODE REVIEW

**Comment by shannon-heh** [comment]
i like the new template, esp the center formatting, buttons, and nice colors! code looks good, just have some suggestions for the template itself:

- since you hyper-linked TigerHub, we should keep it consistent and hyper-link the Dashboard and Course Page, instead of saying "link" below
- i'd prefer if we didn't have the stock photo at the bottom - i think the photo is too big + the image is not really "representative" of tigersnatch. i would prefer just having the tiger icon in the center and maybe in small text, "tigersnatch.com" written undereneath the icon
- don't like capitalization of "Snatch" - it's a little corny
- "Want to -always- stay subscribed until you manually unsubscribe?"

**Review by shannon-heh — CHANGES_REQUESTED** [review]
check out my comment above about changes to the template.

**Comment by nicholaspad** [comment]
Implemented all of your suggestions. Had to reorganize the email-sending code to add hyperlinks into the email (mainly just moving the location of the `for` statement). The code is actually cleaner as a result because much of the wording is moved into the SendGrid template online. Here's screenshots:

### Open spot in course **with** reserved seating + user has auto-resub **on**
yes reserved yes autoresub

### Open spot in course **without** reserved seating + user has auto-resub **on**
no reserved yes autoresub

### Open spot in course **with** reserved seating + user has auto-resub **off**
yes reserved no autoresub

### Open spot in course **without** reserved seating + user has auto-resub **off**
no reserved no autoresub

### The emails are also responsive
IMG_5701

**Comment by nicholaspad** [comment]
@shannon-heh do you think the font size for the P.S. should be smaller? or do you think it looks fine

**Comment by shannon-heh** [comment]
> @shannon-heh do you think the font size for the P.S. should be smaller? or do you think it looks fine

I'd like to make the PS smaller. otherwise, new template looks great

**Review by shannon-heh — APPROVED** [review]

**Pull request merged**
