### PR TITLE
Display basic section subscription stats

### PR DESCRIPTION
**Pull request by nicholaspad**
## Summary

This PR introduces the "Who?" badge to all course pages. The badge, when hovered, displays information about how many of each class year (2023-2026, Grad, Faculty, and Other) are subscribed to a section. **It appears only for sections that have one or more subscription.** The purpose of this feature is to increase the usefulness of the "# Tigers" counter, which reveals the total number of subscriptions for each section.

I propose using our email script to notify all TigerSnatch users of this change, what do you think of this @shannon-heh:

CleanShot 2022-12-23 at 21 51 38@2x

## Design choices

- When a user subscribes or unsubscribes from a section, the badge's tooltip changes to "Reload to see stats!".
    - Dynamically updating the tooltip message it possible, but it requires the user's class year and we'd have to manually parse the message string. A future PR could address this but I don't see it as a must-have.
- I chose to use a tooltip (rather than a modal) to display the data to reduce the number of moving parts on the page. The data is just a "tidbit" of information so I think a tooltip is appropriate.
- Each document in the `users` collection stores the user's `year` as a field that is either `null` or (2023-2026, Grad, Faculty, or Other).
- When a user first visits TigerSnatch, their class year is pulled from the ActiveDirectory API (`/users` endpoint).
    - I retroactively added class year info to all existing user documents via the script at the bottom of `activedirectory.py`.

### Course page with sections with 0 and >0 subscriptions

https://user-images.githubusercontent.com/13815069/209419551-07f243bb-05a1-4b63-aff4-fab0a294f9e9.mp4

## Subscribing to a section

https://user-images.githubusercontent.com/13815069/209419600-778b039c-5980-4de3-a9be-6d7c9191fd4a.mp4

## Unsubscribing from a section

https://user-images.githubusercontent.com/13815069/209419667-49273c80-6079-4a18-b193-bb6beb3d0669.mp4

### CODE REVIEW

**Review by shannon-heh — COMMENTED** [review]
To clarify: When are you planning to send the email about the change?

**Review by shannon-heh — CHANGES_REQUESTED** [review]
I'm not sure about the "Who?" badge. I think it clutters the table if there are a lot of rows, and the gold color/bolding draws unnecessary attention to it. Perhaps we could consider using an black icon instead? Maybe an eye or a person icon. Let me know if you agree.

**Comment by nicholaspad** [comment]
> To clarify: When are you planning to send the email about the change?

@shannon-heh a couple days before add drop period, do you think that's fine

**Comment by nicholaspad** [comment]
> I'm not sure about the "Who?" badge. I think it clutters the table if there are a lot of rows, and the gold color/bolding draws unnecessary attention to it. Perhaps we could consider using an black icon instead? Maybe an eye or a person icon. Let me know if you agree.

really good point, I've changed it to blue person icons. Thoughts?

CleanShot 2022-12-23 at 21 47 48@2x

**Comment by shannon-heh** [comment]
> > To clarify: When are you planning to send the email about the change?
> 
> @shannon-heh a couple days before add drop period, do you think that's fine

Hmm... I don't think we should send a mass email to students, since there are so many people subscribed and the change is not a major feature. I think we can let people discover it on their own, or tack a message onto the open spots email.

**Review by shannon-heh — APPROVED** [review]
lgtm! person icon is much better. see my comment about sending the email

**Pull request merged**
