### PR TITLE
New Account Settings modal

### PR DESCRIPTION
**Pull request by nicholaspad**
## Changelog
* Moved email and phone number change forms into a modal triggered by the new button *Edit Account Settings* (see demo video)
    * This decreases the vertical space that the Notifications panel takes in mobile view, and gives us more room for the planned feature of setting # notifications before auto-unsubscription
* Updated introductory tutorial to reflect the new button (see demo video)

## Demo
https://user-images.githubusercontent.com/13815069/135676175-88840985-ad6e-471a-9ba4-898227ab1063.mov

### CODE REVIEW

**Comment by nicholaspad** [comment]
@shannon-heh @bzzbbz 😄

**Review by shannon-heh — COMMENTED** [review]
q: what happens if you edit both email and phone fields, then click Change only on email or only on phone? does this update both email and phone? could be confusing for user if this is the assumed behavior, but they find out later that either email or phone wasn't actually updated.

also i think we should rethink the fact we're somewhat obscuring the fact that email/phone settings can be changed. i know that we mention setting phone # in the initial tutorial, but people can easily skip the tutorial or forget. i was thinking we can put different icons on Notifications panel, one for email, one for phone, and one for bell (for auto-unsubscribe). clicking on an icon would show the same settings modal, but i guess we could add functionality where, e.g. clicking the phone button would auto-select the phone field. this idea might be excessive but i think it makes more explicit on the main page what settings a user can change.  

but this modal was great idea, good preparation for implementing # notifs before auto-unsubscribe.

**Comment by nicholaspad** [comment]
@shannon-heh Entering text into the email and phone fields and clicking the "Change" button updates only the corresponding field (either email or phone but not both). I agree that this might be confusing for users. I changed the button names to "Change Email" and "Change Phone" to make it clearer that clicking a button updates only that field:

image

**Comment by nicholaspad** [comment]
@shannon-heh I agree with you that we're now obscuring the fact that users can change their email and phone number. I think we should deploy this PR and implement a better UI in a future PR. is this fine?

**Review by shannon-heh — APPROVED** [review]
lgtm! i'll work on ui changes at a later time

**Pull request merged**
